[toolchain]
anchor_version = "0.29.0"

[features]
resolution = true
skip-lint = false

[programs.localnet]
token_transfer = "J8YgpQ4n6mzE9FdiMECZtRPXUKewue1mw76VADRg5jpe"

[registry]
url = "https://api.apr.dev"

[provider]
cluster = "Devnet"
wallet = "./wallet.json"

[scripts]
test = "yarn run ts-mocha -p ./tsconfig.json -t 1000000 tests/**/*.ts"
